### ISSUE TITLE
Crash when loading an effectchain preset

### ISSUE THREAD

**Issue by mevvern** [BespokeSynth/BespokeSynth#1830]
### Expected
- The preset gets applied, in the correct order, to the effectchain with no crash

### Actual
- Bespoke crashes when loading an effectchain preset on an effectchain that has a different set of effects than what's in the preset. 
- Loading an empty preset causes no crash, but it also doesn't clear the effectchain. 
- Loading a preset with the same effects in a different order properly applies the parameters to each effect with no crash, but doesn't change the order of the effects to match what's in the preset.

## Steps to reproduce:
1. Start with an effectchain preset of your choice
2. Create a new effectchain node (can be empty or have a different set of effect types than the preset)
3. Select the preset you chose in step one, and put it on the effectchain. The crash occurs here

## Backtrace:
```
backtrace:
3: UnhandledExceptionFilter + 0x1e7
4: memset + 0x1218
5: _C_specific_handler + 0x96
6: _chkstk + 0x11f
7: RtlRaiseException + 0x484
8: RtlRaiseException + 0x1d7
9: RaiseException + 0x69
24: BaseThreadInitThunk + 0x14
25: RtlUserThreadStart + 0x21
```

## Bespoke info:
```
build: bespoke 1.3.0 (Dec 22 2024 18:35:38))
samplerate: 48000
buffersize: 256
```

## System info:
```
OS: Windows 10
CPU vendor: AuthenticAMD
CPU model: AMD Ryzen 5 7600X 6-Core Processor
CPU speed: 4670 MHz
num cores: 12
num CPUs: 6
RAM: 31865 MB
language: en
region: US
display language: en-US
description: Windows (Desktop)
```

**Comment by NoxyNixie** [comment]
I think this crash may have been fixed in the Nightly builds. Can you test the Nightly build?

**Comment by mevvern** [comment]
Hello. I tested it with the latest nightly build `bespoke NIGHTLY 1.3.0 (Jun 28 2025 20:48:46) - Windows 10 - HEAD 9f2506b` and the crash still happens under the same conditions. I made sure to test it with a new preset made within that version, but that also crashed. The other, potentially related issues i mentioned are still there as well.

**Comment by NoxyNixie** [comment]
Can you provide a savestate and/or prefab file that reproduces this crash?
